### ISSUE TITLE
Modified EntryFromGoQuery function but nothing changed.

### ISSUE THREAD

**Issue by NotHolmes** [gosom/google-maps-scraper#2]
Hi, I'm trying to get a 2nd address from Google Maps (a localized address from each language), the problem is no matter what I added to func EntryFromGoQuery, nothing changes, let alone the 2nd address. 

for example even when I add these lines in `func EntryFromGoQuery` in gmaps/entry.go
```Go
entry.Address_first = "first"
entry.Address_second = "second"
```
(database already modified)
my `results.csv` never changes except the column names and an empty new columns I added, `addr` will always be in the first address column (the original column).
Or even when I'm trying to print something using this function, It just doesn't come out.

Does this mean the script don't use this function at all ? or should I modify somewhere else too to make it work.

Edited : This is irrelevant to the above question but It seems like I need to use 
```el := doc.Find(`button[data-item-id="laddress"]`)``` instead of ```el := doc.Find(`button[data-item-id="address"]`)``` but it doesn't seem to fix the problem anyway because I don't think it can find `laddress` at all. I can only get one address and no `laddress` here and I will have to specify `-lang` to get a localized address of my choice, are there any ways I can get both `address` and `laddress` here. 🤔

**Comment by NotHolmes** [comment]
This is extra but how do you exclude with `headless` option ?

**Comment by gosom** [comment]
Regarding the first topic:

In order to add data to the csv you have to:
a. Add an attribute to the Entry struct (` Address_second string`  in your case).
b. In the `EntryFromGoQuery` function you need to populate this attribute. In order to populate it from the DOM it has to exist. 
c. https://github.com/gosom/google-maps-scraper/blob/main/gmaps/entry.go#L39 you need to add the column name and the value in CsvRow and CsvHeader methods

Regardin addresses, I believe that gmaps only display one address.

About the second topic:
If you want to see the actual browser opening (non-headless) mode use the debug flag:
https://github.com/gosom/google-maps-scraper/tree/main#command-line-options

**Comment by NotHolmes** [comment]
> 
> Regardin addresses, I believe that gmaps only display one address.
> 

This seems to be the problem. Even with `-debug` and my browser shows 2 addresses (`data-item-id="address"` and `data-item-id="laddress"`), gmaps can only get the "address" one.

Anyway, I decided to not use the localized address anymore but I'll try to look into this more when I have time.

Thank you for your answer.

**Comment by gosom** [comment]
When `laddress` exists in the DOM if you use the correct selector then you can get it. 
From my tests, I noticed that laddress is not always there. In that case there is nothing to select. 

not an issue in my opinion. 

I am closing the issue
